//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsTable
    {
        public int AppointmentId { get; set; }
        public int PaitentID { get; set; }
        public int DoctorID { get; set; }
        public string Purpose { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string VisitSummary { get; set; }
    }
}
