//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities1 : DbContext
    {
        public HospitalEntities1()
            : base("name=HospitalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentsTable> AppointmentsTables { get; set; }
        public virtual DbSet<DoctorsTable> DoctorsTables { get; set; }
        public virtual DbSet<MedicationListTable> MedicationListTables { get; set; }
        public virtual DbSet<MessageTable> MessageTables { get; set; }
        public virtual DbSet<PatientTable> PatientTables { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
    }
}
