//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTable
    {
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string UserLoginName { get; set; }
        public int MedicationID { get; set; }
        public int TestID { get; set; }
    }
}
